version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: vpn-postgres
    environment:
      POSTGRES_DB: vpn_db
      POSTGRES_USER: vpn_user
      POSTGRES_PASSWORD: vpn_password
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vpn_user -d vpn_db"]
      interval: 2s
      timeout: 5s
      retries: 10
      start_period: 10s

  vpnbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vpn-bot
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      TELEGRAM_BOT_TOKEN: 8728404030:AAFEy3ziOh6Psu7e13-WB1BR2jsKpzmoQh4
      DATABASE_URL: postgres://vpn_user:vpn_password@postgres:5432/vpn_db?sslmode=disable
      REMNAWAVE_PANEL_URL: https://panel.vynex.one
      REMNAWAVE_API_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiYjk4NzJiZTMtMmNiZi00YzNkLWI4OGUtOGU4YWUyNmExM2YyIiwidXNlcm5hbWUiOm51bGwsInJvbGUiOiJBUEkiLCJpYXQiOjE3NzM0OTYzNjcsImV4cCI6MTA0MTM0MDk5Njd9.B9_knPEgpNhfRjzF02SK0xtp1rf1S6yBBCzXXMYfBGY
      REMNAWAVE_SQUAD_ID: 850f9a30-27a6-4404-8831-1148ca91231b
      CRYPTO_PAY_API_TOKEN: 55155:AA68UjKSGn6IDjS67hbfhhz9RHGAGYzUlD2
      CRYPTO_PAY_TESTNET: 1
      TELEGRAM_ADMIN_ID: 5005319838
      GUIDE_TEXT: asdsad
      # Optional: Telegram Stars prices (positive integers)
      STARS_1_MONTH: 1
      STARS_3_MONTHS: 3
